### PR TITLE
android: upgraded gradle and dependencies

### PR DESCRIPTION
**Pull request by elig0n**
This Android project's gradle version is very old, where the very recent Android Studio 4.2.2 refuses to even work with.
I've selected the minimum possible gradle version (4.8.1) and also had to introduce maven repo for some of its dependencies.
Please consider upgrading (with dependencies as well !) so people don't have hard time joining the development effort

### CODE REVIEW

**Comment by mcastorina** [comment]
@elig0n I appreciate all of your efforts to update this project! I will test these changes locally to make sure it's still working, but updating the versions is definitely a good idea.

**Comment by mcastorina** [comment]
Running `./gradlew assembleDebug` fails with these changes applied.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().
```

I'm not super adept with gradle, so perhaps it's a problem with my system.

**Comment by mcastorina** [comment]
@elig0n let's go ahead and update everything to the latest versions instead of the minimum.

**Comment by elig0n** [comment]
How late? Should we use alpha and rc versions ?

**Comment by mcastorina** [comment]
The latest stable releases, unless you have a strong reason to use alpha / RC versions.

**Comment by mcastorina** [comment]
Thanks!

**Pull request merged**
